# install_longhorn.yml
---
- name: 📀 1 - Preparar discos en nodos de almacenamiento y workers
  import_playbook: playbooks/01_prepare-disks.yml

- name: 🚀 2 - Desplegar Longhorn desde el nodo controlador
  import_playbook: playbooks/02_deploy-longhorn.yml

- name: 🔑 3 - Generar y sellar Secret con autenticación básica
  import_playbook: playbooks/03_generate-auth-secret.yml

- name: 🌐 4 - Crear IngressRoute interno para el dashboard de Longhorn
  import_playbook: playbooks/04_ingress-longhorn-internal.yml

- name: 🌐 Verificar acceso al Dashboard (modo tolerante)
  ansible.builtin.shell: >
    curl -k -u admin:SuperPassword123 https://longhorn.socialdevs.site/dashboard/
    --max-time 10 --silent --output /dev/null --write-out '%{http_code}'
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  register: dashboard_access_check
  failed_when: >
    dashboard_access_check.stdout is defined and
    dashboard_access_check.stdout not in ["200", "302", "401"]
  changed_when: false
  ignore_errors: true