# Ruta: site.yml
---
- name: 📦 Preparar disco de almacenamiento con LVM y exportar NFS
  hosts: storage
  become: true
  gather_facts: false
  roles:
    - role: storage_setup

- name: 💾 Preparar nodos Longhorn (formatear y montar /dev/vdb)
  hosts: workers
  become: true
  gather_facts: false
  roles:
    - role: longhorn_worker

# Instalar herramientas (kubectl, helm) en el nodo controlador
- name: 🚀 Instalar herramientas locales
  import_playbook: playbooks/01_install_local_tools.yml

- name: 🚀 Instalar Longhorn (incluye etiquetado de nodos desde master1)
  import_playbook: playbooks/install_longhorn.yml

- name: ✅ Validar instalación y configuración de Longhorn y nodos
  import_playbook: playbooks/validate_all.yml
