# site.yml
---

- name: 🔐 1 - Generar token JWT en master con permisos correctos
  import_playbook: playbooks/01_generate_token.yml

- name: 🔧 2 - Preparar nodo controlador (kubectl + helm + kubeconfig + token)
  import_playbook: playbooks/02_prepare_controller.yml

- name: 💾 3 - Preparar almacenamiento en nodo storage y workers
  import_playbook: playbooks/03_prepare_storage-workers.yml

- name: 🚀 4 - Desplegar Longhorn desde controller
  import_playbook: playbooks/04_deploy_longhorn.yml

- name: ✅ 5 - Validar clúster y estado de Longhorn
  import_playbook: playbooks/05_validate_cluster.yml
