---
# site.yml
# Playbook principal para configurar almacenamiento con LVM, NFS y Longhorn

- hosts: storage
  become: yes
  gather_facts: yes
  roles:
    - role: storage_setup

- hosts: longhorn_nodes
  become: yes
  gather_facts: yes
  roles:
    - role: longhorn_worker
