---
# roles/storage_setup/tasks/main.yml
# Este rol prepara el disco de datos adicional (/dev/vdb) en nodos de almacenamiento.
# Usa solo tareas raw para compatibilidad con sistemas sin Python (ej. Flatcar Linux)

- name: Verificar existencia del disco /dev/vdb
  raw: test -b /dev/vdb
  register: disk_check
  failed_when: disk_check.rc != 0
  changed_when: false

- name: Crear tabla de particiones GPT
  raw: parted -s /dev/vdb mklabel gpt
  changed_when: false

- name: Crear partición primaria 100%
  raw: parted -s /dev/vdb mkpart primary 0% 100%
  changed_when: false

- name: Esperar a que /dev/vdb1 aparezca
  raw: |
    for i in $(seq 1 5); do
      test -b /dev/vdb1 && exit 0
      sleep 1
    done
    exit 1
  register: wait_partition
  failed_when: wait_partition.rc != 0
  changed_when: false

- name: Crear volumen físico LVM
  raw: pvcreate -ff -y /dev/vdb1
  changed_when: false

- name: Crear grupo de volúmenes
  raw: vgcreate vg_storage /dev/vdb1
  changed_when: false

- name: Crear volumen lógico para PostgreSQL
  raw: lvcreate -y -L 20G -n postgres_lv vg_storage
  changed_when: false

- name: Crear volumen lógico para datos compartidos
  raw: lvcreate -y -L 20G -n shared_lv vg_storage
  changed_when: false

- name: Crear volumen lógico para Longhorn (resto)
  raw: lvcreate -y -l 100%FREE -n longhorn_lv vg_storage
  changed_when: false

- name: Formatear postgres_lv
  raw: mkfs.ext4 -F /dev/vg_storage/postgres_lv
  changed_when: false

- name: Formatear shared_lv
  raw: mkfs.ext4 -F /dev/vg_storage/shared_lv
  changed_when: false

- name: Formatear longhorn_lv
  raw: mkfs.ext4 -F /dev/vg_storage/longhorn_lv
  changed_when: false

- name: Crear directorios para montaje
  raw: mkdir -p /srv/nfs/postgresql /srv/nfs/shared /mnt/longhorn-disk
  changed_when: false

- name: Montar postgres_lv
  raw: mount /dev/vg_storage/postgres_lv /srv/nfs/postgresql
  changed_when: false

- name: Montar shared_lv
  raw: mount /dev/vg_storage/shared_lv /srv/nfs/shared
  changed_when: false

- name: Montar longhorn_lv
  raw: mount /dev/vg_storage/longhorn_lv /mnt/longhorn-disk
  changed_when: false

- name: Instalar servidor NFS
  raw: |
    which exportfs >/dev/null 2>&1 || \
    (apk add nfs-utils || yum install -y nfs-utils || apt-get install -y nfs-kernel-server)
  changed_when: false

- name: Crear archivo /etc/exports
  raw: |
    echo "/srv/nfs/postgresql *(rw,sync,no_subtree_check,no_root_squash)" > /etc/exports
    echo "/srv/nfs/shared *(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports
  changed_when: false

- name: Reiniciar servidor NFS
  raw: |
    (systemctl enable nfs-server && systemctl restart nfs-server) || \
    (rc-service nfs restart)
  changed_when: false