# playbooks/06_deploy_longhorn.yml
---
- name: 6️⃣ Instalar y validar Longhorn con Helm
  hosts: controller
  become: true
  gather_facts: false

  vars:
    kubeconfig_path: "/home/victory/.kube/config"
    helm_bin: "/usr/local/bin/helm"
    longhorn_namespace: "longhorn-system"

  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    KUBECONFIG: "{{ kubeconfig_path }}"

  pre_tasks:

    - name: 🔍 Verificar si existen recursos en el namespace de Longhorn
      raw: |
        /usr/local/bin/kubectl --kubeconfig {{ kubeconfig_path }} get all -n {{ longhorn_namespace }} || true
      register: longhorn_check
      changed_when: false

    - name: ⚠️ Abortamos si hay residuos de Longhorn
      fail:
        msg: |
          ⚠️ El namespace '{{ longhorn_namespace }}' contiene recursos de una instalación anterior.
          🧹 Ejecuta: ansible-playbook playbooks/08_cleanup_longhorn.yml -e "confirm_cleanup=yes"
          Recursos encontrados:
          {{ longhorn_check.stdout }}
      when:
        - "'No resources found' not in longhorn_check.stdout"
        - "'Unable to connect' not in longhorn_check.stdout"

  tasks:

    - name: 📥 Añadir y actualizar repositorio Helm de Longhorn
      raw: |
        {{ helm_bin }} repo add longhorn https://charts.longhorn.io || true
        {{ helm_bin }} repo update

    - name: 🚀 Instalar Longhorn con Helm
      raw: |
        {{ helm_bin }} upgrade --install longhorn longhorn/longhorn \
          --namespace {{ longhorn_namespace }} \
          --create-namespace \
          --wait \
          --timeout 10m0s
      register: longhorn_install
      failed_when: longhorn_install.rc != 0

    - name: ⏳ Esperar readiness de pods
      raw: |
        /usr/local/bin/kubectl --kubeconfig {{ kubeconfig_path }} wait --for=condition=Ready pod -n {{ longhorn_namespace }} --all --timeout=300s
      register: pod_ready
      failed_when: pod_ready.rc != 0

    - name: 📊 Mostrar estado de pods
      raw: |
        /usr/local/bin/kubectl --kubeconfig {{ kubeconfig_path }} get pods -n {{ longhorn_namespace }}
      register: pods

    - name: ✅ Pods desplegados
      debug:
        var: pods.stdout_lines

    - name: 📁 Validar PVCs y PVs
      raw: |
        /usr/local/bin/kubectl --kubeconfig {{ kubeconfig_path }} get pvc -A
        /usr/local/bin/kubectl --kubeconfig {{ kubeconfig_path }} get pv
      register: volumes_info

    - name: 📦 Volúmenes encontrados
      debug:
        var: volumes_info.stdout_lines