# playbooks/fix_traefik_port.yml
---
- name: 🔧  - Asegurar que Traefik exponga el puerto del dashboard
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Ensure Traefik exposes dashboard port
      kubernetes.core.k8s:
        kind: Service
        namespace: kube-system
        name: traefik
        merge_type: merge
        resource_definition:
          spec:
            ports:
              - name: traefik
                port: 9000
                protocol: TCP
                targetPort: 9000
