---
- name: 📜 Generar certificado autofirmado TLS para dominio interno Longhorn
  hosts: controller
  become: true
  gather_facts: false

  vars:
    cert_dir: "/tmp/longhorn-cert"
    tls_secret_name: "internal-tls-secret"
    tls_namespace: "longhorn-system"
    domain_name: "longhorn.socialdevs.site"
    kubeconfig_path: "/home/victory/.kube/config"
    openssl_bin: "/usr/bin/openssl"

  tasks:
    - name: 📁 Crear carpeta temporal para certificados
      file:
        path: "{{ cert_dir }}"
        state: directory
        mode: '0755'

    - name: 🔐 Generar clave privada
      command: "{{ openssl_bin }} genrsa -out {{ cert_dir }}/tls.key 2048"

    - name: 🧾 Generar CSR autofirmado
      command: >
        {{ openssl_bin }} req -x509 -nodes -days 3650
        -subj "/CN={{ domain_name }}"
        -newkey rsa:2048
        -keyout {{ cert_dir }}/tls.key
        -out {{ cert_dir }}/tls.crt

    - name: 📦 Crear secret TLS en Kubernetes
      shell: |
        export KUBECONFIG={{ kubeconfig_path }}
        kubectl -n {{ tls_namespace }} create secret tls {{ tls_secret_name }} \
          --cert={{ cert_dir }}/tls.crt --key={{ cert_dir }}/tls.key \
          --dry-run=client -o yaml | kubectl apply -f -
      register: secret_result

    - name: ✅ Mostrar resultado
      debug:
        var: secret_result.stdout_lines